{% set data= load_setup_py_data() %}
package:
  name: "ts-dream"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_dream = lsst.ts.dream.csc:run_dream

test:
  requires:
    - ts-conda-build =0.4
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
    - ts-xml
  source_files:
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - ts-tcpip
    - ts-xml
